export {
  type WebFingerVerifySurfaceProps,
  WebFingerVerifySurface,
  type WfvResult,
  type WfvResultFail,
  type WfvResultPass,
} from "./WebFingerVerifySurface.js";
export {
  WFV_FAIL_LABEL_RESOLVE,
  WFV_FAIL_LABEL_WHAT,
  WFV_FAIL_RESOLUTION_STEPS,
  WFV_FAIL_DEFAULT_REASON_PREFIX,
  WFV_FAIL_SUBTITLE,
  WFV_FAIL_TITLE,
  WFV_IDLE_BODY,
  WFV_INTRO_HEAD,
  WFV_INTRO_PLACEHOLDER,
  WFV_INTRO_TAIL,
  WFV_LOADING_CTA,
  WFV_PASS_LABEL_ACTOR,
  WFV_PASS_LABEL_FINGERPRINT,
  WFV_PASS_SUBTITLE,
  WFV_PASS_TITLE,
  WFV_RESULT_HEADING,
  WFV_RUN_CTA,
  WFV_STEP1_LABEL,
  WFV_SUBTITLE,
  WFV_TITLE,
  type WfvOutcome,
  type WfvPhase,
} from "./copy.js";
