# Theourgia — task runner recipes
#
# Install just: https://github.com/casey/just
# Run `just` (no args) to list recipes.
# Run `just <recipe>` to execute.

# Defaults
set shell := ["bash", "-euo", "pipefail", "-c"]
set dotenv-load := true

# Show all available recipes
default:
    @just --list --unsorted

# -----------------------------------------------------------------------------
# Bootstrapping
# -----------------------------------------------------------------------------

# Install all backend + frontend dependencies in editable / dev mode
install: install-backend install-frontend
    @echo "✓ install complete"

# Install backend Python deps in a virtualenv via uv
install-backend:
    cd backend && uv sync --all-extras --dev

# Install frontend Node deps via pnpm
install-frontend:
    pnpm install --frozen-lockfile=false

# Bring up the full dev stack (Postgres, Redis, backend, frontend) via Docker
dev:
    docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build

# Bring the dev stack down
down:
    docker compose -f docker-compose.yml -f docker-compose.dev.yml down

# Tail logs from the dev stack
logs *service:
    docker compose -f docker-compose.yml -f docker-compose.dev.yml logs -f {{service}}

# -----------------------------------------------------------------------------
# Linting & formatting
# -----------------------------------------------------------------------------

# Lint everything (Python + JS/TS)
lint: lint-backend lint-frontend
    @echo "✓ lint complete"

# Lint backend (Ruff)
lint-backend:
    cd backend && uv run ruff check .

# Lint frontend (Biome)
lint-frontend:
    pnpm exec biome check .

# Format everything (Python + JS/TS) — modifies files
format: format-backend format-frontend
    @echo "✓ format complete"

# Format backend (Ruff)
format-backend:
    cd backend && uv run ruff format .

# Format frontend (Biome)
format-frontend:
    pnpm exec biome format --write .

# -----------------------------------------------------------------------------
# Type checking
# -----------------------------------------------------------------------------

# Type check everything (mypy + tsc)
typecheck: typecheck-backend typecheck-frontend
    @echo "✓ typecheck complete"

# Type check backend (mypy)
typecheck-backend:
    cd backend && uv run mypy theourgia

# Type check frontend (tsc per workspace)
typecheck-frontend:
    pnpm -r exec tsc --noEmit

# -----------------------------------------------------------------------------
# Testing
# -----------------------------------------------------------------------------

# Run all tests (unit + integration + e2e)
test: test-backend test-frontend
    @echo "✓ test complete"

# Backend test suite (pytest)
test-backend *args:
    cd backend && uv run pytest {{args}}

# Frontend unit tests (Vitest)
test-frontend *args:
    pnpm -r test {{args}}

# End-to-end tests (Playwright)
test-e2e:
    pnpm exec playwright test

# Run tests with coverage
test-coverage:
    cd backend && uv run pytest --cov=theourgia --cov-report=term-missing --cov-report=html

# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------

# Run database migrations forward
migrate:
    cd backend && uv run alembic upgrade head

# Roll back the most recent migration
migrate-down:
    cd backend && uv run alembic downgrade -1

# Create a new migration with autogenerated SQL
migration name:
    cd backend && uv run alembic revision --autogenerate -m "{{name}}"

# Seed the database with development fixtures
seed:
    cd backend && uv run python -m theourgia.scripts.seed

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------

# Build everything (production images)
build: build-backend build-frontend
    @echo "✓ build complete"

# Build backend Docker image
build-backend:
    docker build -f backend/Dockerfile -t theourgia/backend:dev backend/

# Build frontend public site (Astro)
build-frontend:
    pnpm -r --filter ./frontend/* build

# -----------------------------------------------------------------------------
# Docs
# -----------------------------------------------------------------------------

# Run the docs site locally (Astro Starlight)
docs-dev:
    pnpm --filter @theourgia/docs dev

# Build docs site for production
docs-build:
    pnpm --filter @theourgia/docs build

# -----------------------------------------------------------------------------
# Quality / pre-commit
# -----------------------------------------------------------------------------

# Run the full pre-merge check (lint + typecheck + test)
check: lint typecheck test
    @echo "✓ all checks passed"

# Run pre-commit hooks against all files
precommit-all:
    pre-commit run --all-files

# Install pre-commit hooks into the local git repo
precommit-install:
    pre-commit install --install-hooks --hook-type pre-commit --hook-type commit-msg

# -----------------------------------------------------------------------------
# Security
# -----------------------------------------------------------------------------

# Scan for secrets in working tree
secret-scan:
    pnpm exec secretlint "**/*"

# Run dependency vulnerability audits
audit: audit-backend audit-frontend
    @echo "✓ audit complete"

audit-backend:
    cd backend && uv run pip-audit

audit-frontend:
    pnpm audit --prod

# Verify zero-telemetry promise — no outbound network calls in built artifacts
verify-no-telemetry:
    cd backend && uv run python -m theourgia.scripts.verify_no_telemetry

# -----------------------------------------------------------------------------
# Backups (Phase 01 will implement)
# -----------------------------------------------------------------------------

# Run a backup snapshot
backup:
    cd backend && uv run python -m theourgia.scripts.backup

# Restore from a snapshot
restore snapshot:
    cd backend && uv run python -m theourgia.scripts.restore --from {{snapshot}}

# -----------------------------------------------------------------------------
# Identity guard (verifies commits go under the right author)
# -----------------------------------------------------------------------------

# Verify local git config matches an allowed maintainer identity
verify-identity:
    @bash scripts/verify-identity.sh
