apiVersion: v1
kind: Service
metadata:
  name: {{ include "theourgia.fullname" . }}-frontend
  labels:
    {{- include "theourgia.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "theourgia.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
