/**
 * KeyRotationRoute — /settings/keys.
 *
 * Wires the shared KeyRotationSurface to real backend data. The
 * current federation signing keypair lives on the vault-side
 * ActivityPub actor JSON at `/.well-known/webfinger` → `self` link →
 * actor JSON-LD → `publicKey.publicKeyPem`. We fetch that, compute a
 * display SHA-256 fingerprint, and render.
 *
 * Rotation itself is queued behind the envelope-resign worker (b108-2gh):
 * the surface shows the wizard but Begin rotation Toasts the honest
 * status. The whole page is functional as a read-only "here is your
 * current key" surface right now.
 */

import {
  type CurrentKey,
  KeyRotationSurface,
  Toast,
  useAuth,
  useTopbar,
} from "@theourgia/shared";
import { useEffect, useState } from "react";

interface ActorPublicKey {
  publicKey?: { publicKeyPem?: string };
}

async function sha256Fingerprint(pem: string): Promise<string> {
  const enc = new TextEncoder().encode(pem);
  const hash = await crypto.subtle.digest("SHA-256", enc);
  const bytes = Array.from(new Uint8Array(hash));
  const hex = bytes.map((b) => b.toString(16).padStart(2, "0")).join("");
  const chunks = hex.match(/.{1,4}/g) ?? [];
  return `SHA256:${chunks.slice(0, 4).join(" ")} · ${chunks.slice(4, 8).join(" ")}`;
}

function formatDate(iso: string | null | undefined): string {
  if (!iso) return "unknown";
  try {
    return new Date(iso).toLocaleDateString(undefined, {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  } catch {
    return "unknown";
  }
}

export function KeyRotationRoute() {
  useTopbar(
    () => ({
      title: "Federation signing keys",
      subtitle: "The Ed25519 keypair that signs your outbound envelopes",
    }),
    [],
  );

  const auth = useAuth();
  const [current, setCurrent] = useState<CurrentKey | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!auth.session) return;
    const handle =
      auth.session.magickal_name ||
      auth.session.display_name ||
      auth.session.user_id;
    if (!handle) return;

    let cancelled = false;
    (async () => {
      try {
        // Fetch the actor JSON — the same shape federating instances
        // pull to verify our envelope signatures.
        const res = await fetch(`/users/${encodeURIComponent(handle)}`, {
          headers: { Accept: "application/activity+json" },
        });
        if (!res.ok) {
          throw new Error(
            `Actor endpoint returned ${res.status} — federation may not be enabled yet.`,
          );
        }
        const actor = (await res.json()) as ActorPublicKey;
        const pem = actor.publicKey?.publicKeyPem;
        if (!pem) {
          throw new Error(
            "Actor JSON has no publicKey — federation identity not provisioned.",
          );
        }
        const fingerprint = await sha256Fingerprint(pem);
        if (cancelled) return;
        setCurrent({
          fingerprint,
          createdOn: formatDate(null),
          lastUsed: "at the last outbound delivery",
        });
      } catch (e) {
        if (cancelled) return;
        setError(e instanceof Error ? e.message : String(e));
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [auth.session]);

  if (error) {
    return (
      <div style={{ maxWidth: 620, margin: "40px auto", padding: "0 24px" }}>
        <div
          style={{
            padding: "22px 24px",
            border: "1px solid var(--warn-border)",
            background: "var(--warn-soft)",
            borderRadius: "var(--r-lg)",
            fontFamily: "var(--font-ui)",
            color: "var(--warn)",
          }}
        >
          <div style={{ fontWeight: 700, marginBottom: 8 }}>
            Couldn't load your federation key
          </div>
          <div style={{ fontFamily: "var(--font-serif)", fontSize: 14.5, color: "var(--ink-soft)" }}>
            {error}
          </div>
        </div>
      </div>
    );
  }

  if (!current) {
    return (
      <div style={{ maxWidth: 620, margin: "40px auto", padding: "0 24px", color: "var(--ink-mute)" }}>
        Loading current federation key…
      </div>
    );
  }

  return (
    <KeyRotationSurface
      current={current}
      history={[]}
      onBeginRotation={() => {
        Toast.push({
          tone: "info",
          title: "Rotation queued",
          body: "The envelope-resigning worker lands in a follow-up batch. The current key can be regenerated by the operator via CLI in the meantime.",
        });
      }}
      onRevoke={() => {
        Toast.push({
          tone: "warning",
          title: "Emergency revocation queued",
          body: "Revocation is a CLI-only operation for now; open an incident ticket to trigger it operator-side.",
        });
      }}
    />
  );
}
