apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "theourgia.fullname" . }}-celery-worker
  labels:
    {{- include "theourgia.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-worker
spec:
  replicas: {{ .Values.celeryWorker.replicas }}
  selector:
    matchLabels:
      {{- include "theourgia.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-worker
  template:
    metadata:
      labels:
        {{- include "theourgia.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-worker
      {{- if not .Values.secrets.existingSecret }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- include "theourgia.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: celery-worker
          image: {{ include "theourgia.image" (dict "image" .Values.backend.image "chart" .Chart) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - theourgia.workers.app
            - worker
            - --loglevel=info
          env:
            {{- include "theourgia.coreEnv" . | nindent 12 }}
            {{- with .Values.config.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.celeryWorker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
